//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Индивидуалка_ООП
//  @ File Name : Base.h
//  @ Date : 19.10.2018
//  @ Author : Andrew Bondar
//
//



#if !defined(_BASE_H)
#define _BASE_H

#define _CRT_SECURE_NO_WARNINGS
#include <string.h>

class Category;
class Subcategory;
class Goods;

class Base 
{
protected:
	char* name;
public:
	char* getName();
	void setName(char* name);
	Base();
	~Base();

};

#endif  //_BASE_H
