//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Индивидуалка_ООП
//  @ File Name : Base.cpp
//  @ Date : 19.10.2018
//  @ Author : Andrew Bondar
//
//


#include "Base.h"


char* Base::getName() 
{
	return name;
}

void Base::setName(char* arg) 
{
	name = new char[sizeof(arg) + 2];
	strcpy(name, arg);
}

Base::Base() 
{
}
Base::~Base() 
{
    delete name;
}
