//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Индивидуалка_ООП
//  @ File Name : Category.cpp
//  @ Date : 19.10.2018
//  @ Author : Andrew Bondar
//
//
#define _CRT_SECURE_NO_WARNINGS
#include "Category.h"
#include "Subcategory.h"

Category::Category(char* arg) 
{
	name = new char[sizeof(arg)+2];
	strcpy(name, arg);

	this->firstSubcategory = nullptr;
	this->nextItem = nullptr;
	this->numbersOfSubcategories = 0;
}

Category::~Category()
{
	if (this->numbersOfSubcategories != 0)
	{
		Subcategory *link = firstSubcategory, *buff;
		for (int i = 0; i < numbersOfSubcategories; i++)
		{
			buff = link;
			buff->~Subcategory();
			link = link->nextItem;
		}
	}
	//delete this->name;
}
