//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Индивидуалка_ООП
//  @ File Name : Category.h
//  @ Date : 19.10.2018
//  @ Author : Andrew Bondar
//
//


#if !defined(_CATEGORY_H)
#define _CATEGORY_H

#include "Base.h"

class Category : public Base
{
public:
	int numbersOfSubcategories;
	Subcategory* firstSubcategory;
	Category* nextItem;
	Category(char* name);
	~Category();
};

#endif  //_CATEGORY_H
