//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Индивидуалка_ООП
//  @ File Name : Goods.cpp
//  @ Date : 19.10.2018
//  @ Author : Andrew Bondar
//
//

#define _CRT_SECURE_NO_WARNINGS
#include "Goods.h"


int Goods::getAmountOfGoods() 
{
	return amountOfGoods;
}

void Goods::setAmountOfGoods(int arg) 
{
	amountOfGoods = arg;
}

void Goods::setPriceOfGoods(float arg)
{
	priceOfGoods = arg;
}

float Goods::getPriceOfGoods() 
{
	return priceOfGoods;
}

Goods::Goods(char* arg, int amount, float price)
{
	name = new char[sizeof(arg) + 2];
	strcpy(name, arg);

	amountOfGoods = amount;
	priceOfGoods = price;
	this->nextItem = nullptr;
}

Goods::~Goods() 
{
	delete this->name;
}