//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Индивидуалка_ООП
//  @ File Name : Subcategory.h
//  @ Date : 19.10.2018
//  @ Author : Andrew Bondar
//
//


#if !defined(_SUBCATEGORY_H)
#define _SUBCATEGORY_H

#include "Base.h"

class Subcategory : public Base
{
public:
	Subcategory * nextItem;
	Category* categoryOfThis;
	Goods* firstGoods;
	int numberOfGoods;
	Subcategory(char* name);
	~Subcategory();
};

#endif  //_SUBCATEGORY_H
